### ISSUE TITLE
Getting error while wrapping the wasm file: Unexpected end of JSON input

### ISSUE THREAD

**Issue by komalklr** [TrueBitFoundation/truebit-toolchain#6]
**node /truebit-toolchain/modules/emscripten-module-wrapper/prepare.js /workspace/reverse_alphabet/reverse_alphabet.js --file /workspace/reverse_alphabet/alphabet.txt --file /workspace/reverse_alphabet/reverse_alphabet.txt --asmjs --out /workspace/dist**

(node:320) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at processTask (/truebit-toolchain/modules/emscripten-module-wrapper/prepare.js:283:37)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by teutsch** [comment]
Hey @komalklr, thanks for the feedback.  This is a legacy version of the Truebit Toolchain which in not currently maintained.  What sort of task are you trying to build?

**Comment by komalklr** [comment]
ok..I am trying to integrate bulletproofs(Rust) with Truebit.Can I get the current version.I tried building emscripten-module-wrapper and ocaml-offchain from source but that is also giving some dependency error.
Thanks
